export const ItemContents = [
  {
    id: "1",
    point: "8x",
    desc: "on baby, childrens and vitamins^ at SuperPharmacy.*",
    endDate: "2022-10-31",
    img: "/img/01.png",
  },
  {
    id: "2",
    point: "1600",
    desc: "when you spend $60 or more in one transaction at BWS.*",
    endDate: "2022-11-1",
    img: "/img/02.png",
  },
  {
    id: "3",
    point: "4000",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/03.png",
  },
  {
    id: "4",
    point: "5x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/04.png",
  },
  {
    id: "5",
    point: "8x",
    desc: "on baby, childrens and vitamins^ at SuperPharmacy.*",
    endDate: "2022-10-31",
    img: "/img/07.png",
  },
  {
    id: "6",
    point: "3x",
    desc: "when you spend $60 or more in one transaction at BWS.*",
    endDate: "2022-11-1",
    img: "/img/05.png",
  },
  {
    id: "7",
    point: "3200",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/01.png",
  },
  {
    id: "8",
    point: "4x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/04.png",
  },
  {
    id: "9",
    point: "4200",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/05.png",
  },
  {
    id: "10",
    point: "5x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/06.png",
  },
];

