export const ItemContents = [
  {
    id: "1",
    point: "8x",
    desc: "on baby, childrens and vitamins^ at SuperPharmacy.*",
    endDate: "2022-10-31",
    img: "/img/01.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "2",
    point: "1600",
    desc: "when you spend $60 or more in one transaction at BWS.*",
    endDate: "2022-11-1",
    img: "/img/02.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "3",
    point: "4000",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/03.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "4",
    point: "5x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/04.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "5",
    point: "8x",
    desc: "on baby, childrens and vitamins^ at SuperPharmacy.*",
    endDate: "2022-10-31",
    img: "/img/07.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "6",
    point: "3x",
    desc: "when you spend $60 or more in one transaction at BWS.*",
    endDate: "2022-11-1",
    img: "/img/05.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "7",
    point: "3200",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/01.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "8",
    point: "4x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/04.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "9",
    point: "4200",
    desc: "when you spend $60^ or more at healthylife.*",
    endDate: "2022-11-6",
    img: "/img/05.png",
    detailinfo:
      "*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ.",
  },
  {
    id: "10",
    point: "5x",
    desc: "when you shop baby & nursery~ at BIG W.*",
    endDate: "2022-11-6",
    img: "/img/06.png",
    detailinfo:"*Offer runs from 00:01 (local time) 11/10/2022 to 23:59 (local time) 23/10/2022. Offer is available at Woolworths supermarkets, Woolworths Metro and Woolworths Online. Offer is not available on Everyday Market from Woolworths purchases, at any Ampol Woolworths MetroGo or via Metro60. This offer is personal to you and will be available only on your Everyday Rewards Card. Registered Everyday Rewards members must boost their offer to participate in the promotion. To ensure your offer has been added to your Everyday Rewards Card, boost your offer before shopping in-store or online. Any transactions you have made during the promotional period before boosting your offer will not collect 10x points. 10x points equals 1 (one) standard Everyday Rewards point and 9 (nine) additional Everyday Rewards points per dollar spent on products included in this offer. Offer can be enjoyed multiple times. If eligible for multiple points boosters, only 1 (one) standard Everyday Rewards point can be collected once for all eligible offers, plus the applicable number of additional points. To enjoy your offer in-store, you must scan your Everyday Rewards Card before completing the transaction at the checkout. To enjoy your offer online at www.woolworths.com.au you will need to ensure your registered Everyday Rewards Card number is linked to your online account prior to completing your order. Promotional period is based on the local time of the store you shop at in-store or that fulfils your Woolworths Online order. See www.woolworths.com.au for full terms and conditions and delivery areas. Pricing and stock availability may vary by store. Your Everyday Rewards points will be loaded onto your Everyday Rewards Card within 5 business days after each qualifying transaction. This promotion is valid on fresh fruit from the produce department. This promotion excludes juices, sauces, condiments, freezer, dried and canned products that contain fruit or any other product containing fruit that is not a fresh fruit product from the produce department. There are a small number of purchases on which you won't collect points. For details, see this FAQ."
  },
];

